### ISSUE TITLE
Passwords recorded in firewall_logs database table.

### ISSUE THREAD

**Issue by securit** [akaunting/firewall#7]
A suggestion to remove the passwords used by users from the firewall_logs table.

Currently both the username and the attempted password are stored in clear text in the log in the request field. This is considered extremely bad security practice. The suggestion is that you remove or obfuscate the password at a minimum. 

For example 
```
_token=cbgHF2wMw2loK6nNAuEPkhyUod75roFfmjzkZGFp&email=greg@gmail.com&password=SL8dNS)@j!
```

Should be stored something like this:
```
_token=cbgHF2wMw2loK6nNAuEPkhyUod75roFfmjzkZGFp&email=greg@gmail.com&password=**********
```

Or
```
_token=cbgHF2wMw2loK6nNAuEPkhyUod75roFfmjzkZGFp&email=g***@gmail.com&password=**********
```

**Comment by denisdulici** [comment]
Fixed in latest version.

**Comment by danielbehrendt** [comment]
This ist still a problem when used with Livewire / Filament where the password is within the components array of the request:

&components[0][updates][data.password]=FooBar123
